### ISSUE TITLE
[BUG] xtr 0.1.7 not compatible with cargo i18n

### ISSUE THREAD

**Issue by vyskocilm** [woboq/tr#15]
This commit https://github.com/woboq/tr/commit/ddea8408e322e1b1a644f49ca0a28ddc7653ded3#diff-0f053428a9aa17d7f22b4045e4571f52e6892f3aa5d14cd661d64b77295f746dR113 renamed the `--default-domain` to `--domain`, which breaks cargo-i18n. https://github.com/kellpossible/cargo-i18n/blob/fbac992c4a2a655846c03586642481ff7c3fe1ba/i18n-build/src/gettext_impl/mod.rs#L118

Is it possible to revert this change - or recognize the `--default-domain` in addition? Right now the cargo i18n does not work with xtr

```sh
LC_ALL=en_US.UTF-8 cargo i18n
error: unexpected argument '--default-domain' found

  tip: a similar argument exists: '--add-location'

Usage: xtr --copyright-holder <string> --package-name <package> --package-version <version> --add-location <type> <INPUT>...

For more information, try '--help'.
Error: The "xtr" command reported that it was unsuccessful
```

**Comment by ogoffart** [comment]
I'll Fix that asap.

**Comment by ogoffart** [comment]
Thanks for reporting the regression!

I've pushed version xtr 0.1.8
