### ISSUE TITLE
Cannot compile `gettext-sys` when using `gettext` backend.

### ISSUE THREAD

**Issue by rljacobson** [woboq/tr#3]
I ran into Koka/gettext-rs#9, so I changed to `gettext` in my project's `Cargo.toml` like this:

```
[dependencies]
tr = { version = "0.1.3", features = ["gettext"] }
```

The problem is, `tr` still has `gettext-rs` as a dependency and so still tries to compile it. Since the compilation for Gnu gettext fails (it was released when I was 8), so ultimately does the compilation of tr.

Am I doing something wrong, or is there a workaround for this issue?

**Comment by ogoffart** [comment]
gettext-rs is a default feature, you need to disable it using `default-features = false`
let me know if that works.

**Comment by rljacobson** [comment]
Works great. Thanks for the help!
