### ISSUE TITLE
tr macro doesn't parse comments when the string is on a seperate line to the macro invocation

### ISSUE THREAD

**Issue by kellpossible** [woboq/tr#5]
Doesn't work:
```rust
// Comment
tr!(
"String"
);
```

Does work:
```rust
// Comment
tr!("String"
);
```

**Comment by ogoffart** [comment]
This was done to mimic the behavior of xgettext which also do not extract comment if it is not on the line before the sting.
So you'd need to do

```
tr!(
// comment
"String"
);
```

Anyway, i think it indeed make sense to support comment before the tr! token, so i added support for it in commit abe5080

**Comment by kellpossible** [comment]
Ooh right, that makes sense! Thanks for adding it anyway, also I do now seem to like the idea of putting the comment inside the tr statement that you suggest. I guess it will be good to have both ways fully supported to avoid confusion.

Also, by the way I've been working on this crate https://github.com/kellpossible/cargo-i18n which I hope to publish soon after I polish up all the code/comments/docs/tests and implement a couple of convenience macros. Would be interested to hear your thoughts about it
